### ISSUE TITLE
Sending Emails with attachments

### ISSUE THREAD

**Issue by anayra-c6b9** [Punit-Choudhary/Python-beginner-scripts#103]
- **File/Project Name:** SENDING EMAIL
- **What I want to work upon:** I want to create a python script with which the user can send the mail with attachments from the commandline. The script will use the user's email-id and token id for validation.

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** Projects
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by do159hu** [comment]
I can to do this task. Can you assign it to me?

**Comment by anayra-c6b9** [comment]
> I can to do this task. Can you assign it to me?

Hey @do159hu I appreciate your enthusiasm for this project but I have issued this request due to the fact that I have already created this project. I would recommend you to create your own unique issue. Thankyou.

**Comment by anayra-c6b9** [comment]
@Punit-Choudhary I request you to assign this project to me asap. I have more in store. Thank you

**Comment by Punit-Choudhary** [comment]
@anayra-c6b9 Apologies for the delay!
@do159hu You may create another issue and contribute to the project.
How? Read [CONTRIBUTING](https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/CONTRIBUTING.md) and [CONTRIBUTE](https://github.com/Punit-Choudhary/Python-beginner-scripts/tree/main/CONTRIBUTE)
