### ISSUE TITLE
Pyramid Pattern 1 not in proper folder

### ISSUE THREAD

**Issue by Punit-Choudhary** [Punit-Choudhary/Python-beginner-scripts#104]
**Describe the bug**
Pyramid Pattern 1 is not in the proper folder!

**To Reproduce**
1. Go to Patterns/Pyramid_Patterns/Code
2. main.py and readme.md are associated with Pyramid Pattern 1

**Expected behavior**
Main.py and README.md should be inside a folder named: Pyramid_Pattern_1

**Screenshots**
![image](https://user-images.githubusercontent.com/65050160/194001136-c6802415-cec5-4b8e-8985-3bbf036a799b.png)

**Comment by Punit-Choudhary** [comment]
@TrainedPro You wanna patch it?

**Comment by TrainedPro** [comment]
Sure!

**Comment by Punit-Choudhary** [comment]
@TrainedPro Go ahead mate

**Comment by TrainedPro** [comment]
Sorry for it taking so long. Feel free to let me know if there are any other issues that need resolving!

**Comment by Punit-Choudhary** [comment]
Thank you @TrainedPro 💜 🚀
