### ISSUE TITLE
Symbol Pattern 117

### ISSUE THREAD

**Issue by Harshith-19** [Punit-Choudhary/Python-beginner-scripts#109]
- **File/Project Name:** Symbol Pattern 117
- **What I want to work upon:** [Symbol Pattern 117](https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/Patterns/Symbol_Patterns/img/117.PNG)

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** (eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Punit-Choudhary** [comment]
This issue is stale and anyone can comment to claim it!

**Comment by SanskarSh** [comment]
Hey, I would like to work upon this issue.

**Comment by Punit-Choudhary** [comment]
Ok assigning to you!

**Comment by PrajwalGKale** [comment]
## Greetings , **`@Harshith-19`** 
> **I was looking for a repository to contribute to open source and found this one.**
**Can you assign this to me? I'm familiar with the *CPP Programming* . and I would love to do it.**

_-Regards, thanks._
