### ISSUE TITLE
Update README File

### ISSUE THREAD

**Issue by Punit-Choudhary** [Punit-Choudhary/Python-beginner-scripts#11]
Update [README](https://github.com/Punit-Choudhary/Python-beginner-scripts#readme) file for this repo.

**Comment by ThisIsMatin** [comment]
Hi, Can I update your Readme file?

**Comment by batul02** [comment]
I am a Hacktoberfest participant. Would like to contribute to this project and fix this issue. I will arrange and link all the files in Readme.

**Comment by Punit-Choudhary** [comment]
@batul02 Go ahead!
@ThisIsMatin You can contribute to this repo through your python scripts.

**Comment by Punit-Choudhary** [comment]
Issue solved by @batul02
