### ISSUE TITLE
Numeric pattern 3

### ISSUE THREAD

**Issue by canav1** [Punit-Choudhary/Python-beginner-scripts#112]
- **Numeric pattern 3**
- **Add solution of Numeric pattern 3**

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** (eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Atharv-777** [comment]
hey @Punit-Choudhary can i work on it?

**Comment by Punit-Choudhary** [comment]
@Atharv-777 Someone is already working on it.
You may create another issue and contribute to the project.
How? Read [CONTRIBUTING](https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/CONTRIBUTING.md) and [CONTRIBUTE](https://github.com/Punit-Choudhary/Python-beginner-scripts/tree/main/CONTRIBUTE)
