### ISSUE TITLE
News API in python

### ISSUE THREAD

**Issue by SachinDabhade** [Punit-Choudhary/Python-beginner-scripts#119]
- **Projects/News API.py**
- **I want to create a new program of news api in python language**

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** (eg: Math, Patterns, Projects)
- [x] There is no existing issue with this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Marsh-sudo** [comment]
Assign me this kindly

**Comment by Punit-Choudhary** [comment]
@SachinDabhade Apologies for the delay.
@Marsh-sudo Someone is already working on the issue.
You may create another issue and contribute.
How? Read [CONTRIBUTING](https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/CONTRIBUTING.md) and [CONTRIBUTE](https://github.com/Punit-Choudhary/Python-beginner-scripts/tree/main/CONTRIBUTE) find out!

**Comment by Marsh-sudo** [comment]
Already on another one
