### ISSUE TITLE
COUNT-DOWN TIMER

### ISSUE THREAD

**Issue by anayra-c6b9** [Punit-Choudhary/Python-beginner-scripts#122]
- **File/Project Name:** COUNT-DOWN TIMER
- **What I want to work upon:** A counter program which counts the time until the timer ends.

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** Projects
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Marsh-sudo** [comment]
Is this issue open...already worked on it
