### ISSUE TITLE
2048 game using Python

### ISSUE THREAD

**Issue by varous7** [Punit-Choudhary/Python-beginner-scripts#127]
- **File/Project Name:** 2048 game
- **What I want to work upon:** Need to contribute the popular 2048 game using python gui

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** (eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Punit-Choudhary** [comment]
This Issue is stale now and anyone can comment here to claim it!

**Comment by choidf** [comment]
Could I take this issue? @Punit-Choudhary

**Comment by Punit-Choudhary** [comment]
Hey @choidf, I have assigned this issue to you. You may comment here or in our discord server if you need any sort of assistance regarding this.
Happy Coding 💜
