### ISSUE TITLE
Sum of n natural numbers

### ISSUE THREAD

**Issue by ghost** [Punit-Choudhary/Python-beginner-scripts#157]
- **File/Project Name: Sum of n natural numbers **
- **What I want to work upon: Write code to print the sum of n natural numbers**

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category: Math** (eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by SachinHatikankar100** [comment]
Hi @Sussy-Sparssy-69  can you assign this to me

**Comment by Punit-Choudhary** [comment]
Hey @Sussy-Sparssy-69 sorry for the delay!

**Comment by Punit-Choudhary** [comment]
Hey @SachinHatikankar100, There is already someone working on the issue.
You can create your own issue and start contributing!
How? Please read [CONTRIBUTING](https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/CONTRIBUTING.md) and [CONTRIBUTE](https://github.com/Punit-Choudhary/Python-beginner-scripts/tree/main/CONTRIBUTE) to find out.

**Comment by Punit-Choudhary** [comment]
This issue is stale now, anyone can mention to claim it!

**Comment by RKSingh5** [comment]
please review the pull request and merge #195

**Comment by Punit-Choudhary** [comment]
@RKSingh5 Assigned to you, please mention the issue number there!
