### ISSUE TITLE
code to calculate volume of hollow hemisphere

### ISSUE THREAD

**Issue by Aneesh02** [Punit-Choudhary/Python-beginner-scripts#167]
- **File/Project Name: code to calculate the volume of hollow hemisphere**
- **What I want to work upon: Code to calculate the volume of the hollow hemisphere**

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** Math
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by funinkina** [comment]
hey, can i contribute this one?

**Comment by Punit-Choudhary** [comment]
Hey @funinkina, There is already someone working on the issue.
You can create your own issue and start contributing!
How? Please read [CONTRIBUTING](https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/CONTRIBUTING.md) and [CONTRIBUTE](https://github.com/Punit-Choudhary/Python-beginner-scripts/tree/main/CONTRIBUTE) to find out.
