### ISSUE TITLE
HCF of two numbers

### ISSUE THREAD

**Issue by Unknown-Cypher** [Punit-Choudhary/Python-beginner-scripts#179]
- **File/Project Name: HCF of two numbers**
- **What I want to work upon: To calculate HCF of two numbers**

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category: Math** (eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Kadermiyanyedi** [comment]
Hello, can you assign to me?
