### ISSUE TITLE
Factors of a number

### ISSUE THREAD

**Issue by Vedant1280** [Punit-Choudhary/Python-beginner-scripts#182]
- **File/Project Name: Factors of a number**
- **What I want to work upon: Add code to calculate all the factors of a number**

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** 

- [x] Add my script/project
- [x] **Category: Math** (eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by MrJayendra** [comment]
I am interested in this work.
Please assign it to me

**Comment by sabhisharma-ise** [comment]
Please assign this issue!

**Comment by RobinMaheshwary** [comment]
I can do it, So pls assign it to me.

**Comment by Punit-Choudhary** [comment]
Hey @MrJayendra , @sabhisharma-ise, @RobinMaheshwary 👋🏼 
We encourage your enthusiasm toward Open Source 💜 
But, there is someone already working on the issue (assigned to someone already)

You can still contribute to the repo, how?
Read [CONTRIBUTING](https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/CONTRIBUTING.md) and [CONTRIBUTE](https://github.com/Punit-Choudhary/Python-beginner-scripts/tree/main/CONTRIBUTE) to know 😉
