### ISSUE TITLE
Sieve of Eratosthenes

### ISSUE THREAD

**Issue by canav1** [Punit-Choudhary/Python-beginner-scripts#198]
- **File/Project Name: Sieve of Eratosthenes**
- **What I want to work upon: Sieve of Eratosthenes**

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** (eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by bhasinamolika** [comment]
Please assign it to me, I can solve this.

**Comment by AryanKansagara** [comment]
hey there I'd like to contribute to this can i share the c++ solution ?

**Comment by Prisha-Mordia** [comment]
Hey, I would like to work upon this. Could you please assign it to me?

**Comment by Punit-Choudhary** [comment]
Sure, assigned to you!
