### ISSUE TITLE
Symbol Pattern 2

### ISSUE THREAD

**Issue by akshatjain24** [Punit-Choudhary/Python-beginner-scripts#201]
- **File/Project Name: Symbol Pattern 2**
- **What I want to work upon: https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/Patterns/Symbol_Patterns/img/2.PNG**

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to: create code for star pattern 2 in your repo** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category: Symbol** (eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Prisha-Mordia** [comment]
Hey, I would like to work upon this.

**Comment by Punit-Choudhary** [comment]
Assigned to you, happy coding!
