### ISSUE TITLE
alphabeticpattern10

### ISSUE THREAD

**Issue by shubhusion** [Punit-Choudhary/Python-beginner-scripts#219]
- **File/Project Name: alphabeticpattern10**
- **What I want to work upon: https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/Patterns/Alphabetic_Patterns/img/alphabeticpattern10.PNG **

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category: Patterns ** 
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by aman6969** [comment]
please assign this to me @Punit-Choudhary

**Comment by Shubham270301** [comment]
@Punit-Choudhary I have already created a pull request for the issue assigned.

**Comment by aman6969** [comment]
ok @Shubham270301

**Comment by Punit-Choudhary** [comment]
@Shubham270301 please mention the issue number in your PR template

**Comment by Shubham270301** [comment]
> @Shubham270301 please mention the issue number in your PR template
@Punit-Choudhary Issue number is already mentioned in the PR template.

![image](https://user-images.githubusercontent.com/96301987/198587361-7b19d19d-a927-4726-b6a4-fc0f1486d9c2.png)
