### ISSUE TITLE
Menu driven program in python for centimeter to meter and vice versa conversions

### ISSUE THREAD

**Issue by aishwarya0918** [Punit-Choudhary/Python-beginner-scripts#242]
- **File/Project Name:**
- **What I want to work upon:**

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** (eg: Math, Patterns, Projects) Math
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by aishwarya0918** [comment]
Please assign me this issue

**Comment by aishwarya0918** [comment]
Thank-you for assigning me this issue
Kindly please add hacktoberfest tag

**Comment by Punit-Choudhary** [comment]
@aishwarya0918 Please select the category.
Is it for Math or Projects?

**Comment by aishwarya0918** [comment]
It is for Math category.
I have updated the same in issue template above.

**Comment by aishwarya0918** [comment]
#254 added
