### ISSUE TITLE
python code to find volume of triangular pyramid

### ISSUE THREAD

**Issue by aishwarya0918** [Punit-Choudhary/Python-beginner-scripts#243]
- **File/Project Name:**
- **What I want to work upon:**

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** (eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by aishwarya0918** [comment]
Please assign me this issue

**Comment by aishwarya0918** [comment]
#249 Volume of triangular pyramid

**Comment by awantikamallick** [comment]
Hi Punit! could you please assign this issue to me?

**Comment by Punit-Choudhary** [comment]
Hey @awantikamallick
We are glad to see your enthusiasm toward Open Source.
But, someone is already working on this Issue.

You can create your own Issue or look for any other unassigned issue.
Make sure you go through [CONTRIBUTING](https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/CONTRIBUTING.md) and [CONTRIBUTE](https://github.com/Punit-Choudhary/Python-beginner-scripts/tree/main/CONTRIBUTE) before making any Issue or PR.

**Comment by Punit-Choudhary** [comment]
Hey @aishwarya0918 
Please mention this issue in your PR

**Comment by aishwarya0918** [comment]
I have now mentioned the issue in the PR Template.
