### ISSUE TITLE
python code to find area of equilateral triangle

### ISSUE THREAD

**Issue by aishwarya0918** [Punit-Choudhary/Python-beginner-scripts#245]
- **File/Project Name:** Area of equilateral triangle
- **What I want to work on:**

## Instructions

- Use comments and docstrings
- Make a folder if the project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** (eg: Math, Patterns, Projects)
- [x] There is no existing issue with this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife: Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by aishwarya0918** [comment]
Please assign me this issue

**Comment by aishwarya0918** [comment]
Thank-you for assigning me this issue
Kindly please add hacktoberfest tag

**Comment by aishwarya0918** [comment]
#251 Area of equilateral triangle

**Comment by Punit-Choudhary** [comment]
@aishwarya0918 
Please mention this issue in your PR

**Comment by aishwarya0918** [comment]
I have now mentioned the issue in PR template.
Please add hacktoberfest tag to this issue.
