### ISSUE TITLE
python code to calculate perimeter of parallelogram

### ISSUE THREAD

**Issue by aishwarya0918** [Punit-Choudhary/Python-beginner-scripts#246]
- **File/Project Name:**
- **What I want to work upon:**

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** (eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by aishwarya0918** [comment]
Please assign me this issue

**Comment by aishwarya0918** [comment]
Thank-you for assigning me this issue
Kindly please add hacktoberfest tag

**Comment by aishwarya0918** [comment]
#250 perimeter of parallelogram added

**Comment by Punit-Choudhary** [comment]
@aishwarya0918
Please mention this issue in your PR template

**Comment by aishwarya0918** [comment]
I have now mentioned the issue in PR template.
Please add hacktoberfest tag to this issue.

**Comment by Punit-Choudhary** [comment]
@aishwarya0918 Hacktoberfest Accepted 💜 🚀
