### ISSUE TITLE
Area of Triangle using sides

### ISSUE THREAD

**Issue by MrB141107** [Punit-Choudhary/Python-beginner-scripts#257]
- **File/Project Name:** Area of Triangles using sides
- **What I want to work up on:** Maths functions and calculations
      I have made a Python script for the user to calculate the area of triangles using the side measurements, through `Heron's Formula`

## Instructions

- Use comments and docstrings
- Make a folder if the project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** Math
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife: Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

@Punit-Choudhary, I would like you to review my contribution and approve it to create a pull request for your repo.

**Comment by Punit-Choudhary** [comment]
Hey @MrB141107, I have assigned the issue to you!

Happy Coding 💜

**Comment by MrB141107** [comment]
@Punit-Choudhary, Thank you so much for your quick reply! ...
