### ISSUE TITLE
Alphabetic Pattern 2

### ISSUE THREAD

**Issue by SanskarSh** [Punit-Choudhary/Python-beginner-scripts#259]
- **File/Project Name: Alphabetic Pattern 2**
- **What I want to work upon: Add code to draw alphabetic pattern 2**

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** (Patterns)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Punit-Choudhary** [comment]
Hey @SanskarSh, I have assigned the issue to you. Feel free to ask if you need any help with this.
Happy Coding 💜
