### ISSUE TITLE
Symbol Pattern 12

### ISSUE THREAD

**Issue by Nupoor10** [Punit-Choudhary/Python-beginner-scripts#268]
- **File/Project Name:** Symbol Pattern 12
- **What I want to work upon:**  [Pattern 12](https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/Patterns/Symbol_Patterns/img/12.PNG)

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:**  Symbol(eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Nupoor10** [comment]
Can I work on this??

**Comment by Punit-Choudhary** [comment]
Hey @Nupoor10, I have assigned the issue to you!
Happy Coding 💜
