### ISSUE TITLE
Trigonometric Ratios

### ISSUE THREAD

**Issue by MrB141107** [Punit-Choudhary/Python-beginner-scripts#271]
- **File/Project Name:** Trigonometric ratios
- **What I want to work on:** Maths, I want to add a Python script which calculates the trigonometric ratios.

## Instructions

- Use comments and docstrings
- Make a folder if the project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** Math
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife: Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

@Punit-Choudhary, I would like to request you to kindly have a look on my issue.

**Comment by Punit-Choudhary** [comment]
Hey @MrB141107, I have assigned it to you. You may comment here if you need any sort of help regarding this.
