### ISSUE TITLE
Numeric Pattern 1

### ISSUE THREAD

**Issue by SanskarSh** [Punit-Choudhary/Python-beginner-scripts#30]
- **File/Project Name:** Numeric Pattern 1
- **What I want to work upon:** [Numeric Pattern 1](https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/Patterns/Numeric%20Patterns/img/numericpattern1.PNG)

## Instructions

- Use comments and docstrings
- Make a folder if the project contains more than one file
- Lint your code using flake8

**I want to:**

- [x] Add my script/project
- [x] **Category:** Patterns
- [x] There is no existing issue with this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by TrainedPro** [comment]
@Punit-Choudhary This has been open for more than 24 hours

**Comment by Punit-Choudhary** [comment]
Go ahead with it @TrainedPro ✨🚀
