### ISSUE TITLE
Area Of Triangle With 2 Parameters

### ISSUE THREAD

**Issue by TrainedPro** [Punit-Choudhary/Python-beginner-scripts#31]
- **File/Project Name:** area _of_triangle_2.py
- **Current Issue with Code:** It takes 3 parameters and may not be correct as the sides are not sorted
- **What I want to improve:** I want to use only the base and height to calculate the parameter

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Improve Existing Code

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Punit-Choudhary** [comment]
Assigned to you!

**Comment by JayantVashishtha** [comment]
I would love to contribute in this task.

**Comment by Punit-Choudhary** [comment]
@JayantVashishtha It has been already assigned to someone, please claim any other or create a new issue.
Please go through CONTRIBUTING
