### ISSUE TITLE
Numeric Pattern 2

### ISSUE THREAD

**Issue by R-Yash** [Punit-Choudhary/Python-beginner-scripts#33]
- **File/Project Name: Numeric Pattern 2**
- **What I want to work upon: Add code to implement given pattern**

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** 

- [x] Add my script/project
- [x] **Category: Patterns** (eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Punit-Choudhary** [comment]
@R-Yash Assigned to you ✨🚀

**Comment by R-Yash** [comment]
@Punit-Choudhary I am new to open source. What should I include in readme.md file ?

**Comment by Punit-Choudhary** [comment]
Use this [README TEMPLATE](https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/Patterns/README_TEMPLATE.md)

**Comment by Punit-Choudhary** [comment]
Use this Raw template
https://raw.githubusercontent.com/Punit-Choudhary/Python-beginner-scripts/main/Patterns/README_TEMPLATE.md

**Comment by R-Yash** [comment]
@Punit-Choudhary  Ok. I will include that. Thanks for your help
