### ISSUE TITLE
alphabets patterns in python

### ISSUE THREAD

**Issue by avyayjain** [Punit-Choudhary/Python-beginner-scripts#35]
- **File/Project Name:**
- **What I want to work upon:**

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** (eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Punit-Choudhary** [comment]
Missing information, please edit the following details.
- File/Project Name:
- What I want to work upon:

**Comment by Aayush3014** [comment]
Hey, guys i recently started contributing in open source and i'll be glad to make contribution of the program as asked in the issue
Here is my github profile - https://github.com/Aayush3014 
You can check and please let me be a part of the open source community.

**Comment by Punit-Choudhary** [comment]
Hey @Aayush3014 

You are welcome to contribute to the repo.
Please go through Contributing.MD and CONTRIBUTE folder
You can create an issue and we will assign it to you!

**Comment by Punit-Choudhary** [comment]
Hey @avyayjain 

We are closing this issue because:
- File name not specified
- Reason for Issue not specified

You may reopen it when you come up with these.
