### ISSUE TITLE
Symbol Pattern 190 

### ISSUE THREAD

**Issue by Harishrirajendra** [Punit-Choudhary/Python-beginner-scripts#53]
- **File/Project Name:** : Symbol Pattern -190
- **What I want to work upon:**
Write code for Symbol Patttern
## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** (eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Punit-Choudhary** [comment]
This issue is stale and anyone can comment here to claim it.
@Harishrirajendra You may also reclaim it by commenting.

**Comment by nirban07** [comment]
i would like to take on this.
Just to clarify 
Code to make patterns like:
1
1 2
1 2 3
1 2 3 4
?

**Comment by nirban07** [comment]
sure..please assign it to me

**Comment by nirban07** [comment]
@Punit-Choudhary

**Comment by Punit-Choudhary** [comment]
Apologies for the delay, assigned it to you!

**Comment by nirban07** [comment]
@Punit-Choudhary i have made the pull request. Please review and accept
