### ISSUE TITLE
Numberic Pattern Is An Incorrect Folder

### ISSUE THREAD

**Issue by TrainedPro** [Punit-Choudhary/Python-beginner-scripts#65]
- **Documentation File Name:** Patterns
- **What I want to fix:** Incorrect Submission

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Punit-Choudhary** [comment]
Please mention file name or share url

**Comment by TrainedPro** [comment]
@Punit-Choudhary The link is https://github.com/Punit-Choudhary/Python-beginner-scripts/tree/main/Patterns#:~:text=Numeric%20Patterns/Code/Numeric_Pattern_101

**Comment by Punit-Choudhary** [comment]
Thank you for bringing it to our attention, and assigning it to you!

**Comment by TrainedPro** [comment]
I submitted the pull request. Sorry if the labels or the request type is not perfect, there weren't any labels better suited for this. So i just went with documentation

**Comment by Punit-Choudhary** [comment]
Thank you @TrainedPro for drawing our attention to it, it has been patched from my side.
