### ISSUE TITLE
Movie Recommendation

### ISSUE THREAD

**Issue by SahilSatyam** [Punit-Choudhary/Python-beginner-scripts#72]
- **File/Project Name: Movie Recommendation**
- **What I want to work upon: create a python script that would recommend movies based on predetermined emotions.**

## Instructions

- Use comments and docstrings
- Make a folder if the project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category: Project**: Projects
- [x] There is no existing issue with this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by vatsal9117** [comment]
i want to contribute in  this issue is there any space for me?

**Comment by Punit-Choudhary** [comment]
@vatsal9117 Right now it is assigned to @SahilSatyam 
You may ask @SahilSatyam if he is OK with this, or you can wait for the next 12 hours.
@vatsal9117 You can create your own issue for the program you're interested in.
Make sure no one else is working on it or it's already done.

**Comment by vatsal9117** [comment]
@SahilSatyam  if you don't mind i would like contribute on the issue could you assign me ?

**Comment by SahilSatyam** [comment]
yes, you can go ahead with it @vatsal9117
