### ISSUE TITLE
Email Validator

### ISSUE THREAD

**Issue by smit-sms** [Punit-Choudhary/Python-beginner-scripts#78]
- **File/Project Name:** email_validator.py
- **What I want to work upon:** A script that takes input as an email address and checks whether the email address is valid or not.

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** Projects
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Punit-Choudhary** [comment]
Assigned to you.. go ahead mate 💜
