### ISSUE TITLE
Area of a circle/Volume of a sphere

### ISSUE THREAD

**Issue by JBidlack** [Punit-Choudhary/Python-beginner-scripts#89]
- **File/Project Name:**: Area of a circle
- **What I want to work upon:**: Create a new scripts of code that calculates the area of a circle.

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] Math
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Punit-Choudhary** [comment]
One issue one change one PR
Edit the issue, create another one for another change.

**Comment by JBidlack** [comment]
updated
