### ISSUE TITLE
pyramid pattern 20

### ISSUE THREAD

**Issue by saimaheshtaduri** [Punit-Choudhary/Python-beginner-scripts#93]
- **File/Project Name:**
-  pyramid pattern 20
-  img url : https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/Patterns/Pyramid_Patterns/img/pyramidpattern20.PNG

**I want to:**

- [x] Add my script/project
- [x] Math
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by Punit-Choudhary** [comment]
Please mention pattern image url

**Comment by saimaheshtaduri** [comment]
done @Punit-Choudhary
