### ISSUE TITLE
File name validator

### ISSUE THREAD

**Issue by mclmza** [Punit-Choudhary/Python-beginner-scripts#96]
- **File/Project Name:**
- File name validator
- **What I want to work upon:**
I would like to add a script to validate file names

## Instructions

- Use comments and docstrings
- Make folder if project contains more than one file
- Lint your code using flake8

**I want to:** (Please add/remove options as per requirement)

- [x] Add my script/project
- [x] **Category:** (eg: Math, Patterns, Projects)
- [x] There is no existing issue about this script/project
- [x] There is no such script/project in the repo

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - http://pragmaticprogrammer.in/discord

Happy Coding :purple_heart:

**Comment by mogiiee** [comment]
is this issue closed?
